version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  step-two:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
			- run: npm run build

workflows:
    main:
      jobs:
        - step-two
